# SPDX-FileCopyrightText: : 2022 The PyPSA-Earth Authors
#
# SPDX-License-Identifier: CC0-1.0

name: CI-linux

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: "0 5 * * TUE"

env:
  CACHE_NUMBER: 3  # Change this value to manually reset the environment cache

jobs:
  build:
    strategy:
      fail-fast: false  # don't break CI for ubuntu if windows fails before
      matrix:
        include:
          # Matrix required to handle environment caching with Mambaforge
        - os: ubuntu-latest
          label: ubuntu-latest
          prefix: /usr/share/miniconda3/envs/pypsa-earth

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        micromamba-version: '1.5.9-1'
        environment-file: "envs/environment.yaml"
        log-level: debug
        init-shell: bash
        cache-environment: true
        cache-downloads: true

    - name: Fill submodule
      run: |
        git submodule init
        git submodule update

    - name: Create environment cache
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ matrix.prefix }}
        key: ${{ matrix.label }}-conda-${{ hashFiles('envs/environment.yaml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}

    - name: Update environment due to outdated or unavailable cache
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mamba env update -n pypsa-earth -f envs/environment.yaml

    - name: Conda list
      run: |
        conda list

    - name: Test workflow
      run: |
        rm -rf config.yaml
        cp -rf test/config.distribution.test.yaml config.distribution.yaml
        cp -rf pypsa-earth/config.tutorial.yaml config.pypsa-earth.yaml
        snakemake --cores all solve_network
        
    - name: Test workflow brown field
      run: |
        rm -rf config.yaml
        rm -rf pypsa-earth/resources
        rm -rf pypsa-earth/networks
        rm -rf pypsa-earth/results
        rm -rf results
        rm -rf networks
        cp -rf test/config.distribution.test_MA.yaml config.distribution.yaml
        cp -rf test/config.pypsa-earth_MA.yaml config.pypsa-earth.yaml
        snakemake --cores all solve_network

        # - name: Test plotting and summaries
        #   run: |
        #     snakemake --cores all plot_all_p_nom
        #     snakemake --cores all plot_all_summaries
        #     snakemake --cores all make_all_summaries
        #     rm -rf resources/*.nc resources/*.geojson resources/*.h5 networks results
