# SPDX-FileCopyrightText: : 2022 The PyPSA-Earth Authors
#
# SPDX-License-Identifier: CC0-1.0

name: CI-linux

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: "0 5 * * TUE"

env:
  BASE_ENV: envs/environment.yaml

jobs:
  build:
    strategy:
      fail-fast: false  # don't break CI for ubuntu if windows fails before
      matrix:
        include:
          # Matrix required to handle environment caching with Mambaforge
        - os: ubuntu-latest
          label: ubuntu-latest
          prefix: /usr/share/miniconda3/envs/pypsa-earth

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v6

    - name: Use base env file if it was changed
      run: |
        echo "env_file=${{ env.BASE_ENV }}" >> $GITHUB_ENV

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: pypsa-earth
        channel-priority: strict
        conda-remove-defaults: true

    - name: Cache Conda env
      uses: actions/cache@v5
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(format('{0}', env.env_file)) }}
      id: cache-env

    - name: Update environment
      if: steps.cache-env.outputs.cache-hit != 'true'
      run: conda env update -n pypsa-earth -f ${{ env.env_file }}

    - name: Conda list
      run: |
        conda list

    - name: Fill submodule
      run: |
        git submodule init
        git submodule update

    - name: Test workflow
      run: |
        rm -rf config.yaml
        cp -rf test/config.distribution.test.yaml config.distribution.yaml
        cp -rf test/config.tutorial_full.yaml config.pypsa-earth.yaml
        snakemake --cores all solve_network --forceall

    - name: Test workflow brown field
      run: |
        sleep 120
        rm -rf config.yaml
        rm -rf pypsa-earth/resources
        rm -rf pypsa-earth/networks
        rm -rf pypsa-earth/results
        rm -rf results
        rm -rf networks
        cp -rf test/config.distribution.test_MA.yaml config.distribution.yaml
        cp -rf test/config.pypsa-earth_MA.yaml config.pypsa-earth.yaml
        snakemake --cores all add_electricity --forceall

        # - name: Test plotting and summaries
        #   run: |
        #     snakemake --cores all plot_all_p_nom
        #     snakemake --cores all plot_all_summaries
        #     snakemake --cores all make_all_summaries
        #     rm -rf resources/*.nc resources/*.geojson resources/*.h5 networks results
